# Generated by Django 2.2.24 on 2021-11-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0015_auto_20200413_1639'),
    ]

    operations = [
        # migrations.AlterIndexTogether(
        #     name='document',
        #     index_together={('doc_type', 'version', 'label_string')},
        # ),
    ]
